[tox]
envlist = py312
sdistsrc=dist/wing_diagram-*.tar.gz
skip_missing_interpreters=true

[testenv]
deps =
    pytest
setenv =
    USER = dummy
commands =
    # This line tests that the command line tool is callable end-to-end.
    clan_stats --version
    # This line tests that the command line tool is callable as a module.
    python -m clan_stats --version
    pytest tests
